### ISSUE TITLE
创建excel函数中列表生成式的疑问

### ISSUE THREAD

**Issue by canghailpj** [Arlenelalala/ArxivPaper#2]
def create_excel(self):
        wb = xlwt.Workbook()
        [self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]
        wb.save(self.base_path)

    def add_new_sheet(self, sheet_name, wb):
        sheet = wb.add_sheet(sheet_name, cell_overwrite_ok=True)
        [sheet.write(0, i, self.header[i], self.set_style(bold=True))
         for i in range(len(self.header))]
        for i, w in enumerate(self.col_width):
            sheet.col(i).width = w
请问下，上面两个函数中使用的列表生成式有啥讲究呢，因为直接用for循环也可以

**Comment by Arlenelalala** [comment]
你说的“列表生成式”指的是？

**Comment by canghailpj** [comment]
[self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]
[sheet.write(0, i, self.header[i], self.set_style(bold=True))
     for i in range(len(self.header))]
就是这两处，可能概念说错了，列表推导式

**Comment by Arlenelalala** [comment]
因为一个excel下可以建许多个sheet，所以：
1. [self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]
这行是在excel中新建sheet
2. [sheet.write(0, i, self.header[i], self.set_style(bold=True)) for i in range(len(self.header))]
这行是在sheet中添加column

**Comment by Arlenelalala** [comment]
因为add_new_sheet会有复用，所以单独拎出来写了个函数

**Comment by canghailpj** [comment]
那跟直接在for循环中调用在性能上是不是一样的呢：
for sheet_name in self.sheet_names:
&nbsp; &nbsp; &nbsp; &nbsp; self.add_new_sheet(sheet_name, wb)&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arlenelalala"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 下午2:24
收件人:&nbsp;"Arlenelalala/ArxivPaper"<ArxivPaper@noreply.github.com&gt;;
抄送:&nbsp;"沧海"<778376242@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Arlenelalala/ArxivPaper] 创建excel函数中列表生成式的疑问 (#2)




因为一个excel下可以建许多个sheet，所以：
  
[self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]
 这行是在excel中新建sheet
 
[sheet.write(0, i, self.header[i], self.set_style(bold=True)) for i in range(len(self.header))]
 这行是在sheet中添加column

**Comment by Arlenelalala** [comment]
额，所以你是不是在问下面2种是一样的效果？
>  [self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]

> for sheet_name in self.sheet_names:
       self.add_new_sheet(sheet_name, wb) 


A：我只是喜欢把for循环写一行，效果上是一样的。
你可以参考：https://blog.teamtreehouse.com/python-single-line-loops

**Comment by canghailpj** [comment]
对滴，不好意思我可能没咋表述清楚，谢谢哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arlenelalala"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 下午2:34
收件人: "Arlenelalala/ArxivPaper"<ArxivPaper@noreply.github.com&gt;; 
抄送: "沧海"<778376242@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Arlenelalala/ArxivPaper] 创建excel函数中列表生成式的疑问 (#2)




额，所以你是不是在问：
  
[self.add_new_sheet(sheet_name, wb) for sheet_name in self.sheet_names]
 与
 
for sheet_name in self.sheet_names:
 self.add_new_sheet(sheet_name, wb)
 是一样的效果？
  
A：我只是喜欢把for循环写一行，效果上是一样的。
 你可以参考：https://blog.teamtreehouse.com/python-single-line-loops

**Comment by Arlenelalala** [comment]
嘻嘻，那我close了哈～

**Comment by canghailpj** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arlenelalala"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 下午2:36
收件人: "Arlenelalala/ArxivPaper"<ArxivPaper@noreply.github.com&gt;; 
抄送: "沧海"<778376242@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Arlenelalala/ArxivPaper] 创建excel函数中列表生成式的疑问 (#2)




嘻嘻，那我close了哈～
